### ISSUE TITLE
Click "从模块仓库安装"" and then force close.

### ISSUE THREAD

**Issue by Z5X67280** [xzr467706992/Lanthanum_system_toolbox_v2#2]
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
	at android.os.Handler.<init>(Handler.java:209)
	at android.os.Handler.<init>(Handler.java:123)
	at android.widget.ListView.<init>(ListView.java:227)
	at android.widget.ListView.<init>(ListView.java:169)
	at android.widget.ListView.<init>(ListView.java:165)
	at android.widget.ListView.<init>(ListView.java:161)
	at xzr.La.systemtoolbox.b.a.c.run(Unknown Source)
（Log from X-APM）

**Comment by xzr467706992** [comment]
@Z5X67280 Android版本?

**Comment by Z5X67280** [comment]
@xzr467706992
Android 5.1 原生

**Comment by xzr467706992** [comment]
@Z5X67280 无法复现问题 很神秘 怀疑你系统有毒:joy:

**Comment by Z5X67280** [comment]
@xzr467706992 😂

**Comment by Z5X67280** [comment]
@xzr467706992 等等，我试试卸载 Xposed😂
